In [1]:
import numpy as np

## Exercise 1

In [4]:
#a 
A = np.random.randint(1, 10, size = (3,3))

In [5]:
A

array([[5, 2, 4],
       [6, 1, 1],
       [5, 1, 5]])

In [9]:
A.shape

(3, 3)

In [20]:
#b
x1 = A[0]
x2 = A[0,2]


In [21]:
x1

array([5, 2, 4])

In [22]:
np.inner(x1, x2)

array([20,  8, 16])

In [23]:
np.outer(x1, x2)

array([[20],
       [ 8],
       [16]])

In [ ]:
#check the performance of your model 
#X is matrix  

In [24]:
#c
B = A

In [25]:
np.dot(A, B)

array([[57, 16, 42],
       [41, 14, 30],
       [56, 16, 46]])

In [32]:
# d
x = np.array([1, 2, 3])

In [33]:
x

array([1, 2, 3])

In [34]:
x.shape

(3,)

In [36]:
np.dot(A, x)

array([21, 11, 22])

In [37]:
#e
I = np.identity(3)
I = np.eye(3)

In [38]:
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [41]:
D = np.diag(np.diag(A))

In [42]:
D

array([[5, 0, 0],
       [0, 1, 0],
       [0, 0, 5]])

In [45]:
At = np.transpose(A)
Bt = np.transpose(B)

In [46]:
At = A.transpose()
Bt = B.transpose()

In [47]:
At

array([[5, 6, 5],
       [2, 1, 1],
       [4, 1, 5]])

## Exercice 3

In [48]:
def predict(theta, X):
    return(np.dot(X, theta))
def predict(theta, X):
    return(theta @ X)

In [49]:
def error(theta, X, y): 
    return (theta @ X - y)

In [50]:
def error(theta, X, y): 
    return (predict(theta, X) - y)

In [51]:

def cost_fucntion(theta, X, y):
    J = 0
    n = A.shape[0]
    for i in range(n):
        J +=  error(theta, X[i], y[i]) ** 2
    J /= 2
    #return J   #dont need this one 
#element in column i row j, we have 2 loop in the last case

In [ ]:
def gradient(theta, X, y):
    n = X.shape[0]
    p = X.shape[1]