In [29]:
import numpy as np
import pandas as pd

## Exercise 1

In [2]:
#a 
A = np.random.randint(1, 10, size = (3,3))

In [3]:
A

array([[3, 2, 6],
       [5, 9, 6],
       [6, 7, 8]])

In [4]:
A.shape

(3, 3)

In [5]:
#b
x1 = A[0]
x2 = A[0,2]


In [6]:
x1

array([3, 2, 6])

In [7]:
np.inner(x1, x2)

array([18, 12, 36])

In [8]:
np.outer(x1, x2)

array([[18],
       [12],
       [36]])

In [9]:
#check the performance of your model 
#X is matrix  

In [10]:
#c
B = A

In [11]:
np.dot(A, B)

array([[ 55,  66,  78],
       [ 96, 133, 132],
       [101, 131, 142]])

In [12]:
# d
x = np.array([1, 2, 3])

In [13]:
x

array([1, 2, 3])

In [14]:
x.shape

(3,)

In [15]:
np.dot(A, x)

array([25, 41, 44])

In [16]:
#e
I = np.identity(3)
I = np.eye(3)

In [17]:
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [18]:
D = np.diag(np.diag(A))

In [19]:
D

array([[3, 0, 0],
       [0, 9, 0],
       [0, 0, 8]])

In [20]:
At = np.transpose(A)
Bt = np.transpose(B)

In [21]:
At = A.transpose()
Bt = B.transpose()

In [22]:
At

array([[3, 5, 6],
       [2, 9, 7],
       [6, 6, 8]])

## Exercice 3

In [23]:
def predict(theta, X):
    return(np.dot(X, theta))
def predict(theta, X):
    return(theta @ X)

In [24]:
def error(theta, X, y): 
    return (theta @ X - y)

In [25]:
def error(theta, X, y): 
    return (predict(theta, X) - y)

In [26]:

def cost_fucntion(theta, X, y):
    J = 0
    n = A.shape[0]
    for i in range(n):
        J +=  error(theta, X[i], y[i]) ** 2
    J /= 2
    #return J   #dont need this one 
#element in column i row j, we have 2 loop in the last case

In [47]:
def gradient(theta, X, y):
    n = X.shape[0]
    p = X.shape[1]
    G = np.zeros(p)
    for j in range(p):
        for i in range(n):
            err = error(theta, X[i,], y[i])
            G[j] += err * X[i,j]
    return(G)
            


In [49]:
def sgd(X, y, alpha = 0.001, max_iter = 10000, tol = 1e-6):
    n = X.shape[0]
    p = X.shape[1]
    theta = np.zeros(n) #initilize theta
    theta = np.random.multivariate_normal(np.zeros(p), np.eye(p)) #draw values in normal distribution
    new_value = cost_fucntion(theta, X, y)
    it = 0 #initilize the iterrator to 0
    print("Stochastic gradient descent  ")
    while it < max_iter:
        for i in range(n):
            old_value = new_value
            theta = theta - (alpha * error(theta, X[i,], y[i]) * X[i])
            new_value = cost_fucntion
            diff = np.abs(old_value - new_value)
        it += 1 
        if diff < tol:
            break
        print("cost: {}".format(new_value))
    print("Finish in {} iterations".format(it))
    return theta

In [46]:
import os
file = os.path.join(os.getcwd(),"datasets/boston housing/housing.data")

In [42]:
df = pd.read_csv(file, delim_whitespace=True, header=None)

In [43]:
df

0     1      2   3      4      5     6       7   8      9     10  \
0    0.00632  18.0   2.31   0  0.538  6.575  65.2  4.0900   1  296.0  15.3   
1    0.02731   0.0   7.07   0  0.469  6.421  78.9  4.9671   2  242.0  17.8   
2    0.02729   0.0   7.07   0  0.469  7.185  61.1  4.9671   2  242.0  17.8   
3    0.03237   0.0   2.18   0  0.458  6.998  45.8  6.0622   3  222.0  18.7   
4    0.06905   0.0   2.18   0  0.458  7.147  54.2  6.0622   3  222.0  18.7   
..       ...   ...    ...  ..    ...    ...   ...     ...  ..    ...   ...   
501  0.06263   0.0  11.93   0  0.573  6.593  69.1  2.4786   1  273.0  21.0   
502  0.04527   0.0  11.93   0  0.573  6.120  76.7  2.2875   1  273.0  21.0   
503  0.06076   0.0  11.93   0  0.573  6.976  91.0  2.1675   1  273.0  21.0   
504  0.10959   0.0  11.93   0  0.573  6.794  89.3  2.3889   1  273.0  21.0   
505  0.04741   0.0  11.93   0  0.573  6.030  80.8  2.5050   1  273.0  21.0   

         11    12    13  
0    396.90  4.98  24.0  
1    396.90  9.14  21.6  
2    392.83  4.03  34.7  
3    394.63  2.94  33.4  
4    396.90  5.33  36.2  
..      ...   ...   ...  
501  391.99  9.67  22.4  
502  396.90  9.08  20.6  
503  396.90  5.64  23.9  
504  393.45  6.48  22.0  
505  396.90  7.88  11.9  

[506 rows x 14 columns]

In [45]:
df.dtypes

0     float64
1     float64
2     float64
3       int64
4     float64
5     float64
6     float64
7     float64
8       int64
9     float64
10    float64
11    float64
12    float64
13    float64
dtype: object

In [51]:
dataset = np.genfromtxt(file)

In [52]:
dataset

array([[6.3200e-03, 1.8000e+01, 2.3100e+00, ..., 3.9690e+02, 4.9800e+00,
        2.4000e+01],
       [2.7310e-02, 0.0000e+00, 7.0700e+00, ..., 3.9690e+02, 9.1400e+00,
        2.1600e+01],
       [2.7290e-02, 0.0000e+00, 7.0700e+00, ..., 3.9283e+02, 4.0300e+00,
        3.4700e+01],
       ...,
       [6.0760e-02, 0.0000e+00, 1.1930e+01, ..., 3.9690e+02, 5.6400e+00,
        2.3900e+01],
       [1.0959e-01, 0.0000e+00, 1.1930e+01, ..., 3.9345e+02, 6.4800e+00,
        2.2000e+01],
       [4.7410e-02, 0.0000e+00, 1.1930e+01, ..., 3.9690e+02, 7.8800e+00,
        1.1900e+01]])